--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HyperEnte-PHP/JoinMessageForm
build-by-default: true
branches:
- master
projects:
  JoinMessage:
    path: JoinMessage/
    icon: /JoinMessageLOGO.png
...
